# Change these first
owner: dzoladz # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal Website
    url: https://www.derekzoladz.com/
    icon: https://www.derekzoladz.com/img/icon.png
  - name: Koha
    url: $SECRET_SITE
    icon: https://www.derekzoladz.com/img/icon.png
  - name: CuriousitariumDCZ
    url: https://dzoladz.github.io/curiousitarium/
    icon: https://www.derekzoladz.com/img/icon.png
  - name: TEDSIG 2020
    url: https://tedsig.alaoweb.org/
    icon: https://2020.alaoweb.org/img/favicons/favicon.png
  - name: TEDSIG Speculative Library Futures
    url: https://futures.alaoweb.org/
    icon: https://2020.alaoweb.org/img/favicons/favicon.png
  - name: ALAO 2020
    url: https://2020.alaoweb.org/
    icon: https://2020.alaoweb.org/img/favicons/favicon.png

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Live Status
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
